### DISCUSSION TITLE
LP Überprüfe ob Ladevorgang gestartet wurde

### DISCUSSION THREAD

**Discussion by thecem** [ha-puzzles/homeassistant-puzzlepieces#29] [General]
I don´t get it, may you can help me @cschlipf

```yaml
  - condition: state
    entity_id: binary_sensor.evcc_lp_1_charging
    state: "off"
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.helper_lp1_octopus_intelligent_go_active
        state: "off"
      - condition: time
        after: "05:00:00"
        before: "23:55:00"
    alias: Intelligent Go ist aus oder ausserhalb der Intelligent Go Zeit
```

What is the reason to check in an or the state off of `input_boolean.helper_lp1_octopus_intelligent_go_active`

Does this matter?

```yaml

- condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.helper_lp1_octopus_intelligent_go_active
        state: "off"
      - condition: time
        after: "05:00:00"
        before: "23:55:00"
```
